# Generated by Django 3.2.5 on 2021-12-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPOProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ipos/db/images/')),
                ('title', models.CharField(max_length=100)),
                ('listing_exchange', models.CharField(max_length=100)),
                ('broker_name', models.CharField(max_length=100)),
                ('sale_url', models.URLField(blank=True)),
                ('min_price', models.PositiveSmallIntegerField()),
                ('max_price', models.PositiveSmallIntegerField()),
                ('pre_money_valuation', models.PositiveSmallIntegerField()),
                ('min_investment_amount', models.PositiveSmallIntegerField()),
                ('sector', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('sale_date_time', models.DateTimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
