# Generated by Django 3.2.5 on 2021-12-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICOProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_logo', models.ImageField(upload_to='icos/db/images/')),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_url', models.URLField(blank=True)),
                ('tokensale_platform', models.CharField(max_length=100)),
                ('tokensale_url', models.URLField(blank=True)),
                ('token_type', models.CharField(choices=[('COIN', 'Coin'), ('SECURITY', 'Security'), ('UTILITY', 'Utility'), ('NOT_AVAIL', 'N/A')], default='NOT_AVAIL', max_length=9)),
                ('tokensale_registration_deadline', models.DateTimeField()),
                ('tokensale_start_date', models.DateTimeField()),
                ('tokensale_end_date', models.DateTimeField()),
                ('funding_methods', models.CharField(max_length=100)),
                ('excluded_participants', models.CharField(max_length=200)),
                ('min_investment_amount', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
