# Generated by Django 4.0 on 2022-01-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=22, unique=True)),
                ('sector_description', models.CharField(max_length=300)),
            ],
        ),
    ]
