# Generated by Django 4.0 on 2022-01-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0013_alter_equityproject_sector_choice'),
        ('common', '0002_sectorchoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currencies',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='SectorChoices',
            new_name='SectorChoice',
        ),
    ]
