# Generated by Django 4.0 on 2022-01-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
