# Generated by Django 3.2.5 on 2021-12-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertising/carousel/db/images/')),
                ('url', models.URLField(blank=True)),
                ('chapter', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=35)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('END', 'End'), ('NOT_AVAIL', 'N/A')], default='NOT_AVAIL', max_length=9)),
                ('date_to_go', models.DateTimeField()),
                ('date', models.DateField()),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
