# Generated by Django 4.0 on 2022-01-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_alter_carouselads_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselAds',
            new_name='CarouselAd',
        ),
    ]
