# Generated by Django 4.0 on 2022-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_rename_carouselads_carouselad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselad',
            name='chapter',
            field=models.CharField(max_length=35),
        ),
    ]
