# Generated by Django 3.2.5 on 2021-12-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equities/db/images/')),
                ('title', models.CharField(max_length=100)),
                ('loans_type', models.CharField(max_length=100)),
                ('loans_broker', models.CharField(max_length=100)),
                ('loans_url', models.URLField(blank=True)),
                ('loans_amount', models.PositiveSmallIntegerField()),
                ('loans_interest', models.DecimalField(decimal_places=2, max_digits=2)),
                ('contract_period', models.CharField(max_length=20)),
                ('days_to_go', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
