# Generated by Django 3.2.5 on 2021-12-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equities/db/images/')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('end_date', models.DateField(help_text='Day to go + date now')),
                ('currency', models.CharField(choices=[('GBP', 'Pound Sterling'), ('SEK', 'Swedish Krona'), ('EUR', 'Euro'), ('DKK', 'Danish Krone'), ('CZK', 'Czech Krona'), ('CHF', 'Swiss Franc'), ('NOK', 'Norwegian Krone')], default='EUR', max_length=3)),
                ('invested', models.PositiveSmallIntegerField()),
                ('round_money', models.PositiveSmallIntegerField(help_text='Target or Max round')),
                ('pre_money_valuation', models.PositiveSmallIntegerField()),
                ('min_investment_amount', models.PositiveSmallIntegerField()),
                ('sector', models.CharField(choices=[('BasicMats', 'Basic Materials'), ('FinServs', 'Financial Services'), ('ConDef', 'Consumer Defensive'), ('Utilities', 'Utilities'), ('Energy', 'Energy'), ('Technology', 'Technology'), ('ConCyc', 'Consumer Cyclical'), ('RealEst', 'Real Estate'), ('Health', 'Healthcare'), ('Comm', 'Communication Services'), ('Industrials', 'Industrials')], default='NONE', help_text='In classification of yahoo.finance', max_length=11)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('add_date_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
