# Generated by Django 3.2.5 on 2021-12-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityproject',
            name='image',
        ),
    ]
