# Generated by Django 3.2.5 on 2021-12-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0002_remove_equityproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityproject',
            name='image',
            field=models.ImageField(default=0, upload_to='equities/db/images/'),
            preserve_default=False,
        ),
    ]
