# Generated by Django 3.2.5 on 2021-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0003_equityproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityproject',
            name='is_active',
            field=models.CharField(db_index=True, default='', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='equityproject',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
