# Generated by Django 3.2.5 on 2021-12-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0004_auto_20211230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityproject',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=3),
        ),
    ]
