# Generated by Django 4.0 on 2022-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0005_equityproject_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityproject',
            name='currency',
            field=models.CharField(choices=[('GBP', '₤'), ('SEK', 'SEK'), ('EUR', '€'), ('DKK', 'DKK'), ('CZK', 'CZK'), ('CHF', 'CHF'), ('NOK', 'NOK')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='equityproject',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
