# Generated by Django 4.0 on 2022-01-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('equities', '0006_alter_equityproject_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityproject',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.currencies', to_field='currency_abbr'),
        ),
    ]
