# Generated by Django 4.0 on 2022-01-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sectorchoices'),
        ('equities', '0009_equityproject_sector1_alter_equityproject_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityproject',
            name='sector1',
        ),
        migrations.AddField(
            model_name='equityproject',
            name='sector_choice',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.sectorchoices', to_field='sector_name'),
        ),
        migrations.AlterField(
            model_name='equityproject',
            name='sector',
            field=models.CharField(choices=[('BasicMats', 'Basic Materials'), ('FinServs', 'Financial Services'), ('ConDef', 'Consumer Defensive'), ('Utilities', 'Utilities'), ('Energy', 'Energy'), ('Technology', 'Technology'), ('ConCyc', 'Consumer Cyclical'), ('RealEst', 'Real Estate'), ('Health', 'Healthcare'), ('Comm', 'Communication Services'), ('Industrials', 'Industrials')], default='NONE', help_text='In classification of yahoo.finance', max_length=11),
        ),
    ]
