# Generated by Django 4.0 on 2022-01-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sectorchoices'),
        ('equities', '0011_remove_equityproject_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityproject',
            name='sector_choice',
            field=models.ForeignKey(default='NONE', help_text='common.SectorChoices.sector_description', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.sectorchoices', to_field='sector_name'),
        ),
    ]
